<?php

/**
 * @file
 * Webservice mockup of Open Agency
 */
function ting_openformat_webservice_mockup_menu() {
  $items['ting_openformat_webservice'] = array(
    'page callback' => 'ting_openformat_webservice_mockup_request',
    'access callback' => TRUE
  );
  $items['ting_openformat_webservice/test'] = array(
    'page callback' => 'ting_openformat_webservice_test',
    'access callback' => TRUE
  );

  return $items;
}

function ting_openformat_webservice_test() {
  return '<form name="test" action="ting_openformat_webservice" method="POST" target="_blank"><textarea name="xml"></textarea><input type="submit" name="sub" value="submit"/></form>';
}


/**
 * Faking the request and returns result. If other requests are made than on city = københavn an error will be returned.
 * @return String json
 */
function ting_openformat_webservice_mockup_request() {
   if (isset($_POST['xml'])) {
    $data = rawurldecode($_POST['xml']);
  }
  else {
    $data = file_get_contents('php://input');
  }
  $path = drupal_get_path('module', 'ting_openformat_webservice_mockup');
  if( $data ) {
    $envelope = ting_openformat_webservice_mockup_parse_xml($data);
  }
  else {
    echo 'welcome to ting_openformat_webservice mockup';
    return;
  }  
  $request = $envelope->Body->searchRequest;
  // good user
  $results = ( $request->query == 'harry potter');
  drupal_add_http_header('Content-Type', 'application/json');
  if( $results ) {
    $resp = file_get_contents($path.'/results.json');
  }
  else{
    $resp = file_get_contents($path.'/no-results.json');
  }
  print $resp;
}

/**
 * Parsing the request into a xml object
 * @param type request from ting-client
 * @return \SimpleXMLElement
 */
function ting_openformat_webservice_mockup_parse_xml($soap){
  $pattern = "/:?SOAP-ENV:?/";
  $replace = '';
  $xml = preg_replace($pattern, $replace, $soap);

  $envelope = new SimpleXMLElement($xml);
  return $envelope;
}

function ting_openformat_webservice_mockup_access() {
  return TRUE;
}