<?php

/**
 * @file
 * Webservice mockup of Open Agency
 */
function ting_openformat_webservice_mockup_menu() {
  $items['ting_openformat_webservice'] = array(
    'page callback' => 'ting_openformat_webservice_mockup_request',
    'access callback' => TRUE
  );
  $items['ting_openformat_webservice/test'] = array(
    'page callback' => 'ting_openformat_webservice_test',
    'access callback' => TRUE
  );

  return $items;
}

function ting_openformat_webservice_mockup_ting_openformat_actions($type, $entity, $view_mode, $langcode){
  if ($type == 'test'){
    $actions['test2'] = array(
      '#markup' => 'this_is_an_action_2',
      '#weight' => 2,
    );
    $actions['test1'] = array(
      '#markup' => 'this_is_an_action_1',
      '#weight' => 1,
    );

    return $actions;
  }
}

function ting_openformat_webservice_test() {
  return '<form name="test" action="../ting_openformat_webservice" method="POST" target="_blank"><textarea name="xml"></textarea><input type="submit" name="sub" value="submit"/></form>';
}


/**
 * Faking the request and returns result. If other requests are made than on city = københavn an error will be returned.
 * @return String json
 */
function ting_openformat_webservice_mockup_request() {
   if (isset($_POST['xml'])) {
    $data = rawurldecode($_POST['xml']);
  }
  else {
    $data = file_get_contents('php://input');
  }
  $path = drupal_get_path('module', 'ting_openformat_webservice_mockup');
  if( $data ) {
    $envelope = ting_openformat_webservice_mockup_parse_xml($data);
  }
  else {
    echo 'welcome to ting_openformat_webservice mockup';
    return;
  }
  $request = $envelope->Body;
  $query = trim($request->searchRequest->query);
  $file = $path . '/no-results.json';
  drupal_add_http_header('Content-Type', 'application/json');
  $recid_re = '(\d+-(basis|katalog):\d+)';
  $search_recid_re = '/\brec.id=' . $recid_re . '\b/';
  $object_request_re = '/' . $recid_re . '/';

  if (preg_match($search_recid_re, $query, $match) || preg_match($object_request_re, (current($request->getObjectRequest->identifier)), $match)) {
    $got_recid = $path . '/rec.id/' . $match[1] . '.json';

    if (file_exists($got_recid)) {
      $file = $got_recid;
    }
  }
  elseif ($query == 'harry potter' && $request->searchRequest->start == '1') {
    $file = $path . '/results-page2.json';
  }
  elseif ($query == 'harry potter') {
    $file = $path . '/results.json';
  }

  print file_get_contents($file);;
}

/**
 * Parsing the request into a xml object
 * @param type request from ting-client
 * @return \SimpleXMLElement
 */
function ting_openformat_webservice_mockup_parse_xml($soap){
  $pattern = "/:?SOAP-ENV:?/";
  $replace = '';
  $xml = preg_replace($pattern, $replace, $soap);

  $envelope = new SimpleXMLElement($xml);
  return $envelope;
}

function ting_openformat_webservice_mockup_access() {
  return TRUE;
}
